language: generic 
sudo: required

services:
  - docker

before_install:
  - docker build -t rpetty2012/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rpetty2012/react-test npm test -- --coverage

after_success:
  - docker build -t robpetty/multi-client ./client
  - docker build -t robpetty/multi-nginx ./nginx
  - docker build -t robpetty/multi-server ./server
  - docker build -t robpetty/multi-worker ./worker

  # log into docker cli
  # setup encrpyted variables in travis
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # push images to docker from travis
  - docker push rpetty2012/multi-client
  - docker push rpetty2012/multi-nginx
  - docker push rpetty2012/multi-server
  - docker push rpetty2012/multi-wrker