language: generic 
sudo: required

services:
  - docker

before_install:
  - docker build -t rpetty2012/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rpetty2012/react-test npm test -- --coverage

after_success:
  - docker build -t rpetty2012/multi-client ./client
  - docker build -t rpetty2012/multi-nginx ./nginx
  - docker build -t rpetty2012/multi-server ./server
  - docker build -t rpetty2012/multi-worker ./worker

  # log into docker cli
  # setup encrpyted variables in travis
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # push images to docker from travis
  - docker push rpetty2012/multi-client
  - docker push rpetty2012/multi-nginx
  - docker push rpetty2012/multi-server
  - docker push rpetty2012/multi-worker

  # deploy section for Travis to tell EBS grab the project.
deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-353084998536'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY